image: archlinux
packages:
  - podman
  - buildah
  - passt
  - go
sources:
  - https://github.com/go-ap/webfinger
secrets:
  - 3dcea276-38d6-4a7e-85e5-20cbc903e1ea
  - 3f30fd61-e33d-4198-aafb-0ff341e9db1c
tasks:
  - build: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set +x
      cd webfinger
      make all
  - tests: |
      cd webfinger
      make test
  - push_to_github: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set -a +x
      ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      cd webfinger
      git remote add hub git@github.com:go-ap/webfinger
      git push hub --force --all
  - images: |
      test ${BUILD_SUBMITTER} != "git.sr.ht" && complete-build
      set -a +x
      source ~/.buildah.env

      cd webfinger || exit
      make download
      _user=$(id -un)

      echo 'unqualified-search-registries = ["docker.io"]' | sudo tee /etc/containers/registries.conf.d/unq-search.conf
      echo "${_user}:10000:65536" | sudo tee /etc/subuid
      echo "${_user}:10000:65536" | sudo tee /etc/subgid
      podman system migrate

      podman login -u="${BUILDAH_USER}" -p="${BUILDAH_SECRET}" quay.io

      set --

      _sha=$(git rev-parse --short HEAD)
      _branch=$(git branch --points-at=${_sha} | tail -n1 | tr -d '* ')
      _version=$(printf "%s-%s" "${_branch}" "${_sha}")

      _push() {
        _storage=${1:-all}
        make -C images STORAGE="${_storage}" ENV=dev VERSION="${_version}" push

        if [ "${_branch}" = "master" ]; then
            make -C images STORAGE="${_storage}" ENV=qa VERSION="${_version}" push
        fi

        _tag=$(git describe --long --tags || true)
        if [ -n "${_tag}" ]; then
          make -C images STORAGE="${_storage}" ENV=prod VERSION="${_tag}" push
        fi
      }
      _push
      _push fs
      _push sqlite
      _push boltdb
      _push badger
