image: archlinux
packages:
  - go
  - podman
  - buildah
  - aardvark-dns
sources:
  - https://github.com/go-ap/webfinger
secrets:
  - 32610757-76e9-4671-adf1-98163ca8b594
  - 3f30fd61-e33d-4198-aafb-0ff341e9db1c
  - 90ecf226-098f-4d66-befe-1fe462027432
  - 53ebbaf9-664b-4241-9d07-f2f12feee80c
tasks:
  - build: |
      set +x
      cd webfinger
      make all
  - tests: |
      set -a
      cd webfinger
      make test
  - image: |
      set -a +x
      source ~/.buildah.env

      _user=$(id -un)

      echo 'unqualified-search-registries = ["docker.io"]' | sudo tee /etc/containers/registries.conf.d/unq-search.conf
      echo "${_user}:10000:65536" | sudo tee /etc/subuid
      echo "${_user}:10000:65536" | sudo tee /etc/subgid
      podman system migrate

      podman login -u="${BUILDAH_USER}" -p="${BUILDAH_SECRET}" quay.io

      cd webfinger || exit

      _sha=$(git rev-parse --short HEAD)
      _branch=$(git branch --points-at=${_sha} | tail -n1 | tr -d '* ')
      _version=$(printf "%s-%s" "${_branch}" "${_sha}")

      make -C images builder
      _push() {
        _storage=${1:-all}
        make -C images STORAGE="${_storage}" VERSION="${_version}" ENV=dev push

        if [ "${_branch}" = "master" ]; then
            make -C images STORAGE="${_storage}" ENV=qa VERSION="${_version}" push
        fi
        _tag=$(git describe --long --tags || true)
        if [ -n "${_tag}" ]; then
          make -C images STORAGE="${_storage}" ENV=prod VERSION="${_tag}" push
        fi
      }
      _push
      _push fs
      _push badger
      _push boltdb
      _push sqlite
